/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "claves_rpc.h"
#include "claves.h"

bool_t
xdr_Coord (XDR *xdrs, Coord objp)
{
	register int32_t *buf;

	 if (!xdr_opaque (xdrs, objp, 8))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_KeyArg (XDR *xdrs, KeyArg *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->key))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_SetArgs (XDR *xdrs, SetArgs *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->key))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->value1, MAX_STRING))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->N_value2))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->V_value2.V_value2_val, (u_int *) &objp->V_value2.V_value2_len, MAX_ARRAY,
		sizeof (double), (xdrproc_t) xdr_double))
		 return FALSE;
	 if (!xdr_Coord (xdrs, objp->value3))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ModifyArgs (XDR *xdrs, ModifyArgs *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->key))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->value1, MAX_STRING))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->N_value2))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->V_value2.V_value2_val, (u_int *) &objp->V_value2.V_value2_len, MAX_ARRAY,
		sizeof (double), (xdrproc_t) xdr_double))
		 return FALSE;
	 if (!xdr_Coord (xdrs, objp->value3))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_GetReply (XDR *xdrs, GetReply *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->value1, MAX_STRING))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->N_value2))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->V_value2.V_value2_val, (u_int *) &objp->V_value2.V_value2_len, MAX_ARRAY,
		sizeof (double), (xdrproc_t) xdr_double))
		 return FALSE;
	 if (!xdr_Coord (xdrs, objp->value3))
		 return FALSE;
	return TRUE;
}
